// <auto-generated />
using System;
using DataLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLayer.Migrations
{
    [DbContext(typeof(Clinicdbcontext))]
    partial class ClinicdbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataLayer.Entities.AppointmentEntity", b =>
                {
                    b.Property<int>("Appointment_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Appointment_ID"));

                    b.Property<DateTime>("AppointmentDateTime")
                        .HasColumnType("datetime");

                    b.Property<short>("AppointmentDurationMinutes")
                        .HasColumnType("smallint");

                    b.Property<int>("AppointmentTypeID_FK")
                        .HasColumnType("int");

                    b.Property<int>("ClinicID_FK")
                        .HasColumnType("int");

                    b.Property<int>("ConsultationModeID_FK")
                        .HasColumnType("int");

                    b.Property<int>("DoctorID_FK")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PatientID_FK")
                        .HasColumnType("int");

                    b.Property<int>("StatusID_FK")
                        .HasColumnType("int");

                    b.HasKey("Appointment_ID");

                    b.HasIndex("AppointmentTypeID_FK");

                    b.HasIndex("ClinicID_FK");

                    b.HasIndex("ConsultationModeID_FK");

                    b.HasIndex("DoctorID_FK");

                    b.HasIndex("PatientID_FK");

                    b.HasIndex("StatusID_FK");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("DataLayer.Entities.AppointmentStatusEntity", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusID");

                    b.ToTable("AppointmentStatus");
                });

            modelBuilder.Entity("DataLayer.Entities.AppointmentTypeEntity", b =>
                {
                    b.Property<int>("TypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TypeID");

                    b.ToTable("AppointmentType");
                });

            modelBuilder.Entity("DataLayer.Entities.ClinicEntity", b =>
                {
                    b.Property<int>("ClinicID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClinicID"));

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ClinicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeOnly>("End")
                        .HasColumnType("time(0)");

                    b.Property<string>("LocationDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<TimeOnly>("Start")
                        .HasColumnType("time(0)");

                    b.HasKey("ClinicID");

                    b.ToTable("Clinic");
                });

            modelBuilder.Entity("DataLayer.Entities.ConsultationModeEntity", b =>
                {
                    b.Property<int>("ModeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModeID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ModeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ModeID");

                    b.ToTable("ConsultationModes");
                });

            modelBuilder.Entity("DataLayer.Entities.DoctorEntity", b =>
                {
                    b.Property<int>("DoctorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorID"));

                    b.Property<short>("DoctorTypeID_FK")
                        .HasColumnType("smallint");

                    b.Property<int>("EmployeeID_FK")
                        .HasColumnType("int");

                    b.Property<bool>("IsOnCall")
                        .HasColumnType("bit");

                    b.Property<string>("MedicalLicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<short?>("YearsOfExperience")
                        .HasColumnType("smallint");

                    b.HasKey("DoctorID");

                    b.HasIndex("DoctorTypeID_FK");

                    b.HasIndex("EmployeeID_FK")
                        .IsUnique();

                    b.ToTable("Doctor");
                });

            modelBuilder.Entity("DataLayer.Entities.DoctorTypeEntity", b =>
                {
                    b.Property<short>("DoctorTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("DoctorTypeID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("DoctorTypeID");

                    b.ToTable("DoctorTypes");
                });

            modelBuilder.Entity("DataLayer.Entities.EmployeeEntity", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<int>("ClinicID_FK")
                        .HasColumnType("int");

                    b.Property<short>("EmpployeeTypeID_FK")
                        .HasColumnType("smallint");

                    b.Property<string>("NationalID")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("PersonID_FK")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserID_FK")
                        .HasColumnType("int");

                    b.HasKey("EmployeeID");

                    b.HasIndex("ClinicID_FK");

                    b.HasIndex("EmpployeeTypeID_FK");

                    b.HasIndex("PersonID_FK")
                        .IsUnique();

                    b.HasIndex("UserID_FK")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("DataLayer.Entities.EmployeeTypeEntity", b =>
                {
                    b.Property<short>("EmployeeTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("EmployeeTypeID"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EmployeeTypeID");

                    b.ToTable("employeeTypes");
                });

            modelBuilder.Entity("DataLayer.Entities.MedicalRecordEntity", b =>
                {
                    b.Property<int>("MRID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MRID"));

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChronicDiseases")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("PatientID_FK")
                        .HasColumnType("int");

                    b.HasKey("MRID");

                    b.HasIndex("PatientID_FK");

                    b.ToTable("MedicalRecord");
                });

            modelBuilder.Entity("DataLayer.Entities.PatientEntity", b =>
                {
                    b.Property<int>("PatientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientID"));

                    b.Property<string>("EmergencyContactName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmergencyContactPhone")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PatientPersonID_FK")
                        .HasColumnType("int");

                    b.Property<DateOnly>("RegisterDatew")
                        .HasColumnType("date");

                    b.Property<int>("UserID_FK")
                        .HasColumnType("int");

                    b.HasKey("PatientID");

                    b.HasIndex("PatientPersonID_FK")
                        .IsUnique();

                    b.HasIndex("UserID_FK")
                        .IsUnique();

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("DataLayer.Entities.PaymentEntity", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("AppointmentID_FK")
                        .HasColumnType("int");

                    b.Property<int>("DoctorID_FK")
                        .HasColumnType("int");

                    b.Property<int>("PatientPersonID_FK")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime");

                    b.Property<short>("ProviderID_FK")
                        .HasColumnType("smallint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PaymentID");

                    b.HasIndex("AppointmentID_FK")
                        .IsUnique();

                    b.HasIndex("DoctorID_FK");

                    b.HasIndex("PatientPersonID_FK");

                    b.HasIndex("ProviderID_FK");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("DataLayer.Entities.PaymentProviderEntity", b =>
                {
                    b.Property<short>("ProviderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("ProviderID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ProviderID");

                    b.ToTable("PaymentProviders");
                });

            modelBuilder.Entity("DataLayer.Entities.PersonEntity", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<short?>("Age")
                        .HasColumnType("smallint");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ThirdName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PersonID");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("DataLayer.Entities.ScheduleEntity", b =>
                {
                    b.Property<int>("ScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleID"));

                    b.Property<TimeOnly>("ActualEndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("ActualStartTime")
                        .HasColumnType("time");

                    b.Property<int>("EmployeeID_FK")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ScheduleDate")
                        .HasColumnType("date");

                    b.HasKey("ScheduleID");

                    b.HasIndex("EmployeeID_FK");

                    b.ToTable("Schedule");
                });

            modelBuilder.Entity("DataLayer.Entities.UserEntity", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("RoleID_FK")
                        .HasColumnType("smallint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DataLayer.Entities.AppointmentEntity", b =>
                {
                    b.HasOne("DataLayer.Entities.AppointmentTypeEntity", "AppointmentType")
                        .WithMany("Appointments")
                        .HasForeignKey("AppointmentTypeID_FK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataLayer.Entities.ClinicEntity", "Clinic")
                        .WithMany("Appointments")
                        .HasForeignKey("ClinicID_FK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataLayer.Entities.ConsultationModeEntity", "ConsultationMode")
                        .WithMany("Appointments")
                        .HasForeignKey("ConsultationModeID_FK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataLayer.Entities.DoctorEntity", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorID_FK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataLayer.Entities.PatientEntity", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientID_FK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataLayer.Entities.AppointmentStatusEntity", "Status")
                        .WithMany("Appointments")
                        .HasForeignKey("StatusID_FK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppointmentType");

                    b.Navigation("Clinic");

                    b.Navigation("ConsultationMode");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("DataLayer.Entities.DoctorEntity", b =>
                {
                    b.HasOne("DataLayer.Entities.DoctorTypeEntity", "DoctorType")
                        .WithMany("Doctors")
                        .HasForeignKey("DoctorTypeID_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Entities.EmployeeEntity", "Employee")
                        .WithOne("Doctor")
                        .HasForeignKey("DataLayer.Entities.DoctorEntity", "EmployeeID_FK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DoctorType");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DataLayer.Entities.EmployeeEntity", b =>
                {
                    b.HasOne("DataLayer.Entities.ClinicEntity", "Clinic")
                        .WithMany("Employees")
                        .HasForeignKey("ClinicID_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Entities.EmployeeTypeEntity", "EmpployeeType")
                        .WithMany("Employees")
                        .HasForeignKey("EmpployeeTypeID_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Entities.PersonEntity", "Person")
                        .WithOne("Employee")
                        .HasForeignKey("DataLayer.Entities.EmployeeEntity", "PersonID_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Entities.UserEntity", "User")
                        .WithOne("Employees")
                        .HasForeignKey("DataLayer.Entities.EmployeeEntity", "UserID_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("EmpployeeType");

                    b.Navigation("Person");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataLayer.Entities.MedicalRecordEntity", b =>
                {
                    b.HasOne("DataLayer.Entities.PatientEntity", "Patient")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("PatientID_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DataLayer.Entities.PatientEntity", b =>
                {
                    b.HasOne("DataLayer.Entities.PersonEntity", "PatientPerson")
                        .WithOne("Patient")
                        .HasForeignKey("DataLayer.Entities.PatientEntity", "PatientPersonID_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Entities.UserEntity", "User")
                        .WithOne("Patient")
                        .HasForeignKey("DataLayer.Entities.PatientEntity", "UserID_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatientPerson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataLayer.Entities.PaymentEntity", b =>
                {
                    b.HasOne("DataLayer.Entities.AppointmentEntity", "Appointment")
                        .WithOne("Payment")
                        .HasForeignKey("DataLayer.Entities.PaymentEntity", "AppointmentID_FK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataLayer.Entities.DoctorEntity", "Doctor")
                        .WithMany("Payments")
                        .HasForeignKey("DoctorID_FK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataLayer.Entities.PersonEntity", "PatientPersonID")
                        .WithMany("Payments")
                        .HasForeignKey("PatientPersonID_FK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataLayer.Entities.PaymentProviderEntity", "Provider")
                        .WithMany("Payments")
                        .HasForeignKey("ProviderID_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Doctor");

                    b.Navigation("PatientPersonID");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("DataLayer.Entities.ScheduleEntity", b =>
                {
                    b.HasOne("DataLayer.Entities.EmployeeEntity", "Employee")
                        .WithMany("Schedules")
                        .HasForeignKey("EmployeeID_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DataLayer.Entities.AppointmentEntity", b =>
                {
                    b.Navigation("Payment");
                });

            modelBuilder.Entity("DataLayer.Entities.AppointmentStatusEntity", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("DataLayer.Entities.AppointmentTypeEntity", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("DataLayer.Entities.ClinicEntity", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("DataLayer.Entities.ConsultationModeEntity", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("DataLayer.Entities.DoctorEntity", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("DataLayer.Entities.DoctorTypeEntity", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("DataLayer.Entities.EmployeeEntity", b =>
                {
                    b.Navigation("Doctor");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("DataLayer.Entities.EmployeeTypeEntity", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("DataLayer.Entities.PatientEntity", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("MedicalRecords");
                });

            modelBuilder.Entity("DataLayer.Entities.PaymentProviderEntity", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("DataLayer.Entities.PersonEntity", b =>
                {
                    b.Navigation("Employee");

                    b.Navigation("Patient");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("DataLayer.Entities.UserEntity", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
